dist: trusty
sudo: required
language: c
compiler:
  - gcc
before_install:
  - git clone git://git.cryptomilk.org/projects/cmocka.git 
  - cd cmocka
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - cd ../../

  - git clone https://github.com/vinbero/libgenc
  - cd libgenc
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - cd ../../

  - git clone https://github.com/vinbero/libfastdl
  - cd libfastdl
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - cd ../../

install:
  - sudo apt-get install -y libjansson-dev

  - cd cmocka/build
  - make && sudo make install
  - cd ../../

  - cd libgenc/build
  - make && sudo make install
  - cd ../../

  - cd libfastdl/build
  - make && sudo make install
  - cd ../../

before_script:
  - cmake -version
  - make --version 
  - gcc --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..

script: make && ctest --verbose
